name: AntiAura
version: 0.3
description: Checks for Aura
author: maciekmm
main: tk.maciekmm.antiaura.AntiAura
depend: [ProtocolLib]
commands:
  auracheck:
    description: Check if player has aura hack
    usage: /<command> <nickname> (running/standing) - checks for aura hack
    aliases: [ac]
    permission: auracheck.check